config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/ads'

  get 'admin' => 'admin#index'

  controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
  end

  get 'admin/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  resources :sessions
  resources :users
  resources :orders
  resources :line_items
  resources :carts
  get 'store/index'

  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'products#index'
  root 'store#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bootcont</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <nav class="navbar navbar-success">
  
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Hussain's Store</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/">My Page</a></li>
      <li><a href="/store/index">Store</a></li>
      <li><a href="/login">Login</a></li>
      <% if session[:user_id] %>
      <li><%= link_to 'Orders', orders_path %></li>
      <li><%= link_to 'Carts', carts_path %></li>
      <li><a href="/line_items">Line Item</a></li>
      <li><%= link_to 'Products', products_path %></li>
      <li><%= link_to 'Users', users_path %></li>
      <li><%= button_to 'Logout', logout_path, method: :delete , class:"btn btn-default" %></li>
      <% end %>
    </ul>

    </nav>
    <div>
    <%= yield %>
    
    </div>
  </body>
</html>